config/routes.rb
Rails.application.routes.draw do
  get "log_in" => "sessions#new" , :as => "log_in"
  get "log_out" => "sessions#destroy" , :as => "log_out"
  resources :sessions

  get "sign_up" => "users#new" , :as => "sign_up"
  root :to => "posts#index"
  resources :users

  resources :posts do
    resources :comments
  end

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post, presence: true
  validates :post_id, :body, presence: true 
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, :body, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true , :uniqueness => {:case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #protect_from_forgery with: :exception
  protect_from_forgery
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if
        session[:user_id]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(comment_params[:post_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js # create.js.erb
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Successfully signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password_digest, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<blockquote>
  <p><%= comment.body %></p>
  <p><strong>Posted by <a href="#">Start Bootstrap</a> <%= time_ago_in_words comment.created_at %></strong></p>
</blockquote>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <h2 class="section-heading">Post ID</h2>
      <div class="form-group">
        <input type="number height:1px" class="form-control" name="comment[post_id]" id="comment_post_id" value="<%= @comment.post_id %>"></input>
      </div>
    </div>
    <div class="field">
      <h2 class="section-heading">CONTENT</h2>
      <div class="form-group">
        <textarea type="text" rows="10" class="form-control" name="comment[body]" id="comment_body"><%= @comment.body %></textarea>
      </div>
    </div>
    <div class="actions btn btn-xl">
      <button type="submit" class="btn btn-xl">Submit</button>
    </div>

<% end%>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>");
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>Editing Comment</h1>
          <h2 class="subheading">Shysie</h2>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</article>

<hr>

app/views/comments/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/home-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Comments</h1>
          <hr class="small">
          <span class="subheading">Shysie</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

      <% @comments.each do |comment| %>
          <div class="post-preview">
            <a href="comments/<%= comment.id %>">
              <div class="col-md-3">
                <p style="font-size:30px"><strong><%= comment.post_id %></strong></p>
              </div>
              <div class="col-md-9">
                <p style="font-size:30px"><%= comment.body %></p>
              </div>
            </a>
            <div class="col-lg-12 text-left">
              <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> <%= time_ago_in_words comment.created_at %> ago</p>
              <%= link_to 'Edit', edit_comment_path(comment) %> |
              <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
              <hr>
            </div>
          </div>


      <% end %>
      <%= link_to 'New Comment', new_comment_path %>

      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="#">Older Comments &rarr;</a>
        </li>
      </ul>

    </div>
  </div>
</div>

<hr>

app/views/comments/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>New Comment</h1>
          <h2 class="subheading">Shysie</h2>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Comment Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</article>

<hr>

app/views/comments/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>Post： <%= @comment.post_id %></h1>

        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <p id="notice"><%= notice %></p>
        <p><%= @comment.body %></p>
        <p>Posted by <a href="#">Start Bootstrap</a> <%= time_ago_in_words @comment.created_at %> ago</p>
      <td><%= link_to 'Edit', edit_comment_path(@comment) %></td> |
      <td><%= link_to 'Back', comments_path %></td>

    </div>
  </div>
  </div>
</article>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MyBlog</title>

  <!-- Bootstrap Core CSS -->
  <link href="/assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="/assets/clean-blog.min.css" rel="stylesheet">

  <!-- Custom Fonts -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "#{name}" %>
<% end %>

<!-- Navigation -->
<nav id = "user_nav" class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/">Home</a>
        </li>
        <li>
          <a href="/posts/new">New Post</a>
        </li>
        <% if current_user %>
            <li>
              <a><%= current_user.email %></a>
            </li>
            <li>
              <a href="/log_out">Log out</a>
            </li>
        <% else %>
            <li>
              <a href="/sign_up">Sign up</a>
            </li>
            <li>
              <a href="/log_in">Log in</a>
            </li>
        <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

<%= yield %>

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="https://twitter.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
          <li>
            <a href="https://github.com/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
      </div>
    </div>
  </div>
</footer>

<!-- jQuery -->
<script src="/assets/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/assets/bootstrap.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="/assets/clean-blog.min.js"></script>

</body>

</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <h2 class="section-heading">TITLE</h2>
      <div class="form-group">
        <textarea rows="1" class="form-control" name="post[title]" id="post_title"><%= @post.title %></textarea>
      </div>
    </div>
    <div class="field">
      <h2 class="section-heading">CONTENT</h2>
      <div class="form-group">
        <textarea rows="20" class="form-control" name="post[body]" id="post_body"><%= @post.body %></textarea>
      </div>
    </div>
    <div class="actions btn btn-xl">
      <button type="submit" class="btn btn-xl">Submit</button>
    </div>

<% end%>

app/views/posts/edit.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>Editing Post</h1>
          <h2 class="subheading">Shysie</h2>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</article>

<hr>

app/views/posts/index.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image :url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>MyBlog</h1>
          <hr class="small">
          <span class="subheading">Shysie</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

      <% @posts.reverse.each do |post| %>
          <div class="post-preview">
            <a href="posts/<%= post.id %>">
              <h2 class="post-title"><%= post.title %></h2>
              <h3 class="post-subtitle"><%= post.body %></h3>
            </a>
            <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> <%= time_ago_in_words post.created_at %> ago</p>
            <%= link_to 'Edit', edit_post_path(post) %> |
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <hr>
      <% end %>

      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="#">Older Posts &rarr;</a>
        </li>
      </ul>

    </div>
  </div>
</div>

<hr>

app/views/posts/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>New Post</h1>
          <h2 class="subheading">Shysie</h2>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <%= render 'form' %>

      </div>
    </div>
  </div>
</article>

<hr>

app/views/posts/show.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/post-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading">Shysie</h2>
          <span class="meta">Posted by <a href="#">Start Bootstrap</a> <%= time_ago_in_words @post.created_at %> ago</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <p style="font-size:30px"><%= @post.body %></p>
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>

        <h2 class="section-heading">Comments</h2>
        <div id="comments">
          <%= render :partial => @post.comments.reverse %>
        </div>

        <%= form_for [@post, @post.comments.new], remote: true do |new| %>
            <h3>New Comment</h3>
            <%= new.hidden_field :post_id %>
            <div class="form-group">
              <textarea rows="6" class="form-control" name="comment[body]" id="commeny_body"></textarea>
            </div>
            <button type="submit" class="btn btn-xl">Add Comment</button>
        <% end%>

      </div>
    </div>
  </div>
</article>

<hr>

app/views/users/new.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/contact-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>Sign Up</h1>
          <hr class="small">
          <span class="subheading">Shysie's Blog</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>Want to get in touch with me? Fill out the form below to Sign Up!</p>
      <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
      <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
      <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
      <%= form_for @user do |f| %>
          <% if @user.errors.any? %>
              <div class = "error_messages" >
                <h2>Form is invalid</h2>
                <ul>
                  <% for message in @user.errors.full_messages %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>

          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Email</label>
              <input type="email" class="form-control" placeholder="Email" name="user[email]" id="user_email" required data-validation-required-message="Please enter your email.">
            </div>
          </div>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Password</label>
              <input type="password" class="form-control" placeholder="Password" name="user[password]" id="user_password" required data-validation-required-message="Please enter your password.">
            </div>
          </div>
          <div class="row control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Password Confirmation</label>
              <input type="password" class="form-control" placeholder="Password Confirmation" name="user[password_confirmation]" id="user_password_confirmation" required data-validation-required-message="Please enter your password again.">
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="row">
            <div class="form-group col-xs-12">
              <button type="submit" name="commit" class="btn btn-default">Sign Up</button>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<hr>